export const timezones = [
  { id: 1, name: '(GMT-11) Pacific/Niue' },
  { id: 2, name: '(GMT-11) Pacific/Pago Pago' },
  { id: 3, name: '(GMT-10) Pacific/Honolulu' },
  { id: 4, name: '(GMT-10) Pacific/Rarotonga' },
  { id: 5, name: '(GMT-10) Pacific/Tahiti' },
  { id: 6, name: '(GMT-9.5) Pacific/Marquesas' },
  { id: 7, name: '(GMT-9) America/Adak' },
  { id: 8, name: '(GMT-9) Pacific/Gambier' },
  { id: 9, name: '(GMT-8) America/Anchorage' },
  { id: 10, name: '(GMT-8) America/Juneau' },
  { id: 11, name: '(GMT-8) America/Metlakatla' },
  { id: 12, name: '(GMT-8) America/Nome' },
  { id: 13, name: '(GMT-8) America/Sitka' },
  { id: 14, name: '(GMT-8) America/Yakutat' },
  { id: 15, name: '(GMT-8) Pacific/Pitcairn' },
  { id: 16, name: '(GMT-7) America/Dawson' },
  { id: 17, name: '(GMT-7) America/Fort Nelson' },
  { id: 18, name: '(GMT-7) America/Hermosillo' },
  { id: 19, name: '(GMT-7) America/Los Angeles' },
  { id: 20, name: '(GMT-7) America/Phoenix' },
  { id: 21, name: '(GMT-7) America/Tijuana' },
  { id: 22, name: '(GMT-7) America/Vancouver' },
  { id: 23, name: '(GMT-7) America/Whitehorse' },
  { id: 24, name: '(GMT-6) America/Belize' },
  { id: 25, name: '(GMT-6) America/Boise' },
  { id: 26, name: '(GMT-6) America/Cambridge Bay' },
  { id: 27, name: '(GMT-6) America/Chihuahua' },
  { id: 28, name: '(GMT-6) America/Costa Rica' },
  { id: 29, name: '(GMT-6) America/Denver' },
  { id: 30, name: '(GMT-6) America/Edmonton' },
  { id: 31, name: '(GMT-6) America/El Salvador' },
  { id: 32, name: '(GMT-6) America/Guatemala' },
  { id: 33, name: '(GMT-6) America/Inuvik' },
  { id: 34, name: '(GMT-6) America/Managua' },
  { id: 35, name: '(GMT-6) America/Mazatlan' },
  { id: 36, name: '(GMT-6) America/Ojinaga' },
  { id: 37, name: '(GMT-6) America/Regina' },
  { id: 38, name: '(GMT-6) America/Swift Current' },
  { id: 39, name: '(GMT-6) America/Tegucigalpa' },
  { id: 40, name: '(GMT-6) America/Yellowknife' },
  { id: 41, name: '(GMT-6) Pacific/Easter' },
  { id: 42, name: '(GMT-6) Pacific/Galapagos' },
  { id: 43, name: '(GMT-5) America/Bahia Banderas' },
  { id: 44, name: '(GMT-5) America/Bogota' },
  { id: 45, name: '(GMT-5) America/Cancun' },
  { id: 46, name: '(GMT-5) America/Chicago' },
  { id: 47, name: '(GMT-5) America/Eirunepe' },
  { id: 48, name: '(GMT-5) America/Guayaquil' },
  { id: 49, name: '(GMT-5) America/Indiana/Knox' },
  { id: 50, name: '(GMT-5) America/Indiana/Tell City' },
  { id: 51, name: '(GMT-5) America/Jamaica' },
  { id: 52, name: '(GMT-5) America/Lima' },
  { id: 53, name: '(GMT-5) America/Matamoros' },
  { id: 54, name: '(GMT-5) America/Menominee' },
  { id: 55, name: '(GMT-5) America/Merida' },
  { id: 56, name: '(GMT-5) America/Mexico City' },
  { id: 57, name: '(GMT-5) America/Monterrey' },
  { id: 58, name: '(GMT-5) America/North Dakota/Beulah' },
  { id: 59, name: '(GMT-5) America/North Dakota/Center' },
  { id: 60, name: '(GMT-5) America/North Dakota/New Salem' },
  { id: 61, name: '(GMT-5) America/Panama' },
  { id: 62, name: '(GMT-5) America/Rainy River' },
  { id: 63, name: '(GMT-5) America/Rankin Inlet' },
  { id: 64, name: '(GMT-5) America/Resolute' },
  { id: 65, name: '(GMT-5) America/Rio Branco' },
  { id: 66, name: '(GMT-5) America/Winnipeg' },
  { id: 67, name: '(GMT-4) America/Asuncion' },
  { id: 68, name: '(GMT-4) America/Barbados' },
  { id: 69, name: '(GMT-4) America/Boa Vista' },
  { id: 70, name: '(GMT-4) America/Campo Grande' },
  { id: 71, name: '(GMT-4) America/Caracas' },
  { id: 72, name: '(GMT-4) America/Cuiaba' },
  { id: 73, name: '(GMT-4) America/Detroit' },
  { id: 74, name: '(GMT-4) America/Grand Turk' },
  { id: 75, name: '(GMT-4) America/Guyana' },
  { id: 76, name: '(GMT-4) America/Havana' },
  { id: 77, name: '(GMT-4) America/Indiana/Indianapolis' },
  { id: 78, name: '(GMT-4) America/Indiana/Marengo' },
  { id: 79, name: '(GMT-4) America/Indiana/Petersburg' },
  { id: 80, name: '(GMT-4) America/Indiana/Vevay' },
  { id: 81, name: '(GMT-4) America/Indiana/Vincennes' },
  { id: 82, name: '(GMT-4) America/Indiana/Winamac' },
  { id: 83, name: '(GMT-4) America/Iqaluit' },
  { id: 84, name: '(GMT-4) America/Kentucky/Louisville' },
  { id: 85, name: '(GMT-4) America/Kentucky/Monticello' },
  { id: 86, name: '(GMT-4) America/La Paz' },
  { id: 87, name: '(GMT-4) America/Manaus' },
  { id: 88, name: '(GMT-4) America/Martinique' },
  { id: 89, name: '(GMT-4) America/New York' },
  { id: 90, name: '(GMT-4) America/Nipigon' },
  { id: 91, name: '(GMT-4) America/Pangnirtung' },
  { id: 92, name: '(GMT-4) America/Port-au-Prince' },
  { id: 93, name: '(GMT-4) America/Porto Velho' },
  { id: 94, name: '(GMT-4) America/Puerto Rico' },
  { id: 95, name: '(GMT-4) America/Santiago' },
  { id: 96, name: '(GMT-4) America/Santo Domingo' },
  { id: 97, name: '(GMT-4) America/Thunder Bay' },
  { id: 98, name: '(GMT-4) America/Toronto' },
  { id: 99, name: '(GMT-3) America/Araguaina' },
  { id: 100, name: '(GMT-3) America/Argentina/Buenos Aires' },
  { id: 101, name: '(GMT-3) America/Argentina/Catamarca' },
  { id: 102, name: '(GMT-3) America/Argentina/Cordoba' },
  { id: 103, name: '(GMT-3) America/Argentina/Jujuy' },
  { id: 104, name: '(GMT-3) America/Argentina/La Rioja' },
  { id: 105, name: '(GMT-3) America/Argentina/Mendoza' },
  { id: 106, name: '(GMT-3) America/Argentina/Rio Gallegos' },
  { id: 107, name: '(GMT-3) America/Argentina/Salta' },
  { id: 108, name: '(GMT-3) America/Argentina/San Juan' },
  { id: 109, name: '(GMT-3) America/Argentina/San Luis' },
  { id: 110, name: '(GMT-3) America/Argentina/Tucuman' },
  { id: 111, name: '(GMT-3) America/Argentina/Ushuaia' },
  { id: 112, name: '(GMT-3) America/Bahia' },
  { id: 113, name: '(GMT-3) America/Belem' },
  { id: 114, name: '(GMT-3) America/Cayenne' },
  { id: 115, name: '(GMT-3) America/Fortaleza' },
  { id: 116, name: '(GMT-3) America/Glace Bay' },
  { id: 117, name: '(GMT-3) America/Goose Bay' },
  { id: 118, name: '(GMT-3) America/Halifax' },
  { id: 119, name: '(GMT-3) America/Maceio' },
  { id: 120, name: '(GMT-3) America/Moncton' },
  { id: 121, name: '(GMT-3) America/Montevideo' },
  { id: 122, name: '(GMT-3) America/Paramaribo' },
  { id: 123, name: '(GMT-3) America/Punta Arenas' },
  { id: 124, name: '(GMT-3) America/Recife' },
  { id: 125, name: '(GMT-3) America/Santarem' },
  { id: 126, name: '(GMT-3) America/Sao Paulo' },
  { id: 127, name: '(GMT-3) America/Thule' },
  { id: 128, name: '(GMT-3) Antarctica/Palmer' },
  { id: 129, name: '(GMT-3) Antarctica/Rothera' },
  { id: 130, name: '(GMT-3) Atlantic/Bermuda' },
  { id: 131, name: '(GMT-3) Atlantic/Stanley' },
  { id: 132, name: '(GMT-2.5) America/St Johns' },
  { id: 133, name: '(GMT-2) America/Miquelon' },
  { id: 134, name: '(GMT-2) America/Noronha' },
  { id: 135, name: '(GMT-2) America/Nuuk' },
  { id: 136, name: '(GMT-2) Atlantic/South Georgia' },
  { id: 137, name: '(GMT-1) Atlantic/Cape Verde' },
  { id: 138, name: '(GMT+0) Africa/Abidjan' },
  { id: 139, name: '(GMT+0) Africa/Bissau' },
  { id: 140, name: '(GMT+0) Africa/Monrovia' },
  { id: 141, name: '(GMT+0) Africa/Sao Tome' },
  { id: 142, name: '(GMT+0) America/Danmarkshavn' },
  { id: 143, name: '(GMT+0) America/Scoresbysund' },
  { id: 144, name: '(GMT+0) Atlantic/Azores' },
  { id: 145, name: '(GMT+0) Atlantic/Reykjavik' },
  { id: 146, name: '(GMT+1) Africa/Algiers' },
  { id: 147, name: '(GMT+1) Africa/Casablanca' },
  { id: 148, name: '(GMT+1) Africa/El Aaiun' },
  { id: 149, name: '(GMT+1) Africa/Lagos' },
  { id: 150, name: '(GMT+1) Africa/Ndjamena' },
  { id: 151, name: '(GMT+1) Africa/Tunis' },
  { id: 152, name: '(GMT+1) Atlantic/Canary' },
  { id: 153, name: '(GMT+1) Atlantic/Faroe' },
  { id: 154, name: '(GMT+1) Atlantic/Madeira' },
  { id: 155, name: '(GMT+1) Europe/Dublin' },
  { id: 156, name: '(GMT+1) Europe/Lisbon' },
  { id: 157, name: '(GMT+1) Europe/London' },
  { id: 158, name: '(GMT+2) Africa/Cairo' },
  { id: 159, name: '(GMT+2) Africa/Ceuta' },
  { id: 160, name: '(GMT+2) Africa/Johannesburg' },
  { id: 161, name: '(GMT+2) Africa/Juba' },
  { id: 162, name: '(GMT+2) Africa/Khartoum' },
  { id: 163, name: '(GMT+2) Africa/Maputo' },
  { id: 164, name: '(GMT+2) Africa/Tripoli' },
  { id: 165, name: '(GMT+2) Africa/Windhoek' },
  { id: 166, name: '(GMT+2) Antarctica/Troll' },
  { id: 167, name: '(GMT+2) Europe/Amsterdam' },
  { id: 168, name: '(GMT+2) Europe/Andorra' },
  { id: 169, name: '(GMT+2) Europe/Belgrade' },
  { id: 170, name: '(GMT+2) Europe/Berlin' },
  { id: 171, name: '(GMT+2) Europe/Brussels' },
  { id: 172, name: '(GMT+2) Europe/Budapest' },
  { id: 173, name: '(GMT+2) Europe/Copenhagen' },
  { id: 174, name: '(GMT+2) Europe/Gibraltar' },
  { id: 175, name: '(GMT+2) Europe/Kaliningrad' },
  { id: 176, name: '(GMT+2) Europe/Luxembourg' },
  { id: 177, name: '(GMT+2) Europe/Madrid' },
  { id: 178, name: '(GMT+2) Europe/Malta' },
  { id: 179, name: '(GMT+2) Europe/Monaco' },
  { id: 180, name: '(GMT+2) Europe/Oslo' },
  { id: 181, name: '(GMT+2) Europe/Paris' },
  { id: 182, name: '(GMT+2) Europe/Prague' },
  { id: 183, name: '(GMT+2) Europe/Rome' },
  { id: 184, name: '(GMT+2) Europe/Stockholm' },
  { id: 185, name: '(GMT+2) Europe/Tirane' },
  { id: 186, name: '(GMT+2) Europe/Vienna' },
  { id: 187, name: '(GMT+2) Europe/Warsaw' },
  { id: 188, name: '(GMT+2) Europe/Zurich' },
  { id: 189, name: '(GMT+3) Africa/Nairobi' },
  { id: 190, name: '(GMT+3) Asia/Amman' },
  { id: 191, name: '(GMT+3) Asia/Baghdad' },
  { id: 192, name: '(GMT+3) Asia/Beirut' },
  { id: 193, name: '(GMT+3) Asia/Damascus' },
  { id: 194, name: '(GMT+3) Asia/Famagusta' },
  { id: 195, name: '(GMT+3) Asia/Gaza' },
  { id: 196, name: '(GMT+3) Asia/Hebron' },
  { id: 197, name: '(GMT+3) Asia/Jerusalem' },
  { id: 198, name: '(GMT+3) Asia/Nicosia' },
  { id: 199, name: '(GMT+3) Asia/Qatar' },
  { id: 200, name: '(GMT+3) Asia/Riyadh' },
  { id: 201, name: '(GMT+3) Europe/Athens' },
  { id: 202, name: '(GMT+3) Europe/Bucharest' },
  { id: 203, name: '(GMT+3) Europe/Chisinau' },
  { id: 204, name: '(GMT+3) Europe/Helsinki' },
  { id: 205, name: '(GMT+3) Europe/Istanbul' },
  { id: 206, name: '(GMT+3) Europe/Kiev' },
  { id: 206, name: '(GMT+3) Europe/Kirov' },
  { id: 207, name: '(GMT+3) Europe/Minsk' },
  { id: 208, name: '(GMT+3) Europe/Moscow' },
  { id: 209, name: '(GMT+3) Europe/Riga' },
  { id: 210, name: '(GMT+3) Europe/Simferopol' },
  { id: 211, name: '(GMT+3) Europe/Sofia' },
  { id: 212, name: '(GMT+3) Europe/Tallinn' },
  { id: 213, name: '(GMT+3) Europe/Uzhgorod' },
  { id: 214, name: '(GMT+3) Europe/Vilnius' },
  { id: 215, name: '(GMT+3) Europe/Volgograd' },
  { id: 216, name: '(GMT+3) Europe/Zaporozhye' },
  { id: 217, name: '(GMT+4) Asia/Baku' },
  { id: 218, name: '(GMT+4) Asia/Dubai' },
  { id: 219, name: '(GMT+4) Asia/Tbilisi' },
  { id: 220, name: '(GMT+4) Asia/Yerevan' },
  { id: 221, name: '(GMT+4) Europe/Astrakhan' },
  { id: 222, name: '(GMT+4) Europe/Samara' },
  { id: 223, name: '(GMT+4) Europe/Saratov' },
  { id: 224, name: '(GMT+4) Europe/Ulyanovsk' },
  { id: 225, name: '(GMT+4) Indian/Mahe' },
  { id: 226, name: '(GMT+4) Indian/Mauritius' },
  { id: 227, name: '(GMT+4) Indian/Reunion' },
  { id: 228, name: '(GMT+4.5) Asia/Kabul' },
  { id: 229, name: '(GMT+4.5) Asia/Tehran' },
  { id: 230, name: '(GMT+5) Antarctica/Mawson' },
  { id: 231, name: '(GMT+5) Asia/Aqtau' },
  { id: 232, name: '(GMT+5) Asia/Aqtobe' },
  { id: 233, name: '(GMT+5) Asia/Ashgabat' },
  { id: 234, name: '(GMT+5) Asia/Atyrau' },
  { id: 235, name: '(GMT+5) Asia/Dushanbe' },
  { id: 236, name: '(GMT+5) Asia/Karachi' },
  { id: 237, name: '(GMT+5) Asia/Oral' },
  { id: 238, name: '(GMT+5) Asia/Qyzylorda' },
  { id: 239, name: '(GMT+5) Asia/Samarkand' },
  { id: 240, name: '(GMT+5) Asia/Tashkent' },
  { id: 241, name: '(GMT+5) Asia/Yekaterinburg' },
  { id: 242, name: '(GMT+5) Indian/Kerguelen' },
  { id: 243, name: '(GMT+5) Indian/Maldives' },
  { id: 244, name: '(GMT+5.5) Asia/Colombo' },
  { id: 245, name: '(GMT+5.5) Asia/Kolkata' },
  { id: 246, name: '(GMT+5.75) Asia/Kathmandu' },
  { id: 247, name: '(GMT+6) Antarctica/Vostok' },
  { id: 248, name: '(GMT+6) Asia/Almaty' },
  { id: 249, name: '(GMT+6) Asia/Bishkek' },
  { id: 250, name: '(GMT+6) Asia/Dhaka' },
  { id: 251, name: '(GMT+6) Asia/Omsk' },
  { id: 252, name: '(GMT+6) Asia/Qostanay' },
  { id: 253, name: '(GMT+6) Asia/Thimphu' },
  { id: 254, name: '(GMT+6) Asia/Urumqi' },
  { id: 255, name: '(GMT+6) Indian/Chagos' },
  { id: 256, name: '(GMT+6.5) Asia/Yangon' },
  { id: 257, name: '(GMT+6.5) Indian/Cocos' },
  { id: 258, name: '(GMT+7) Antarctica/Davis' },
  { id: 259, name: '(GMT+7) Asia/Bangkok' },
  { id: 260, name: '(GMT+7) Asia/Barnaul' },
  { id: 261, name: '(GMT+7) Asia/Ho Chi Minh' },
  { id: 262, name: '(GMT+7) Asia/Hovd' },
  { id: 263, name: '(GMT+7) Asia/Jakarta' },
  { id: 264, name: '(GMT+7) Asia/Krasnoyarsk' },
  { id: 265, name: '(GMT+7) Asia/Novokuznetsk' },
  { id: 266, name: '(GMT+7) Asia/Novosibirsk' },
  { id: 267, name: '(GMT+7) Asia/Pontianak' },
  { id: 268, name: '(GMT+7) Asia/Tomsk' },
  { id: 269, name: '(GMT+7) Indian/Christmas' },
  { id: 270, name: '(GMT+8) Asia/Brunei' },
  { id: 271, name: '(GMT+8) Asia/Choibalsan' },
  { id: 272, name: '(GMT+8) Asia/Hong Kong' },
  { id: 273, name: '(GMT+8) Asia/Irkutsk' },
  { id: 274, name: '(GMT+8) Asia/Kuala Lumpur' },
  { id: 275, name: '(GMT+8) Asia/Kuching' },
  { id: 276, name: '(GMT+8) Asia/Macau' },
  { id: 277, name: '(GMT+8) Asia/Makassar' },
  { id: 278, name: '(GMT+8) Asia/Manila' },
  { id: 279, name: '(GMT+8) Asia/Shanghai' },
  { id: 280, name: '(GMT+8) Asia/Singapore' },
  { id: 281, name: '(GMT+8) Asia/Taipei' },
  { id: 282, name: '(GMT+8) Asia/Ulaanbaatar' },
  { id: 283, name: '(GMT+8) Australia/Perth' },
  { id: 284, name: '(GMT+8.75) Australia/Eucla' },
  { id: 285, name: '(GMT+9) Asia/Chita' },
  { id: 286, name: '(GMT+9) Asia/Dili' },
  { id: 287, name: '(GMT+9) Asia/Jayapura' },
  { id: 288, name: '(GMT+9) Asia/Khandyga' },
  { id: 289, name: '(GMT+9) Asia/Pyongyang' },
  { id: 290, name: '(GMT+9) Asia/Seoul' },
  { id: 291, name: '(GMT+9) Asia/Tokyo' },
  { id: 292, name: '(GMT+9) Asia/Yakutsk' },
  { id: 293, name: '(GMT+9) Pacific/Palau' },
  { id: 294, name: '(GMT+9.5) Australia/Adelaide' },
  { id: 295, name: '(GMT+9.5) Australia/Broken Hill' },
  { id: 296, name: '(GMT+9.5) Australia/Darwin' },
  { id: 297, name: '(GMT+10) Antarctica/Macquarie' },
  { id: 298, name: '(GMT+10) Asia/Ust-Nera' },
  { id: 299, name: '(GMT+10) Asia/Vladivostok' },
  { id: 301, name: '(GMT+10) Australia/Brisbane' },
  { id: 302, name: '(GMT+10) Australia/Hobart' },
  { id: 303, name: '(GMT+10) Australia/Lindeman' },
  { id: 304, name: '(GMT+10) Australia/Melbourne' },
  { id: 305, name: '(GMT+10) Australia/Sydney' },
  { id: 306, name: '(GMT+10) Pacific/Chuuk' },
  { id: 307, name: '(GMT+10) Pacific/Guam' },
  { id: 308, name: '(GMT+10) Pacific/Port Moresby' },
  { id: 309, name: '(GMT+10.5) Australia/Lord Howe' },
  { id: 310, name: '(GMT+11) Antarctica/Casey' },
  { id: 311, name: '(GMT+11) Asia/Magadan' },
  { id: 312, name: '(GMT+11) Asia/Sakhalin' },
  { id: 313, name: '(GMT+11) Asia/Srednekolymsk' },
  { id: 314, name: '(GMT+11) Pacific/Bougainville' },
  { id: 315, name: '(GMT+11) Pacific/Efate' },
  { id: 316, name: '(GMT+11) Pacific/Guadalcanal' },
  { id: 317, name: '(GMT+11) Pacific/Kosrae' },
  { id: 318, name: '(GMT+11) Pacific/Norfolk' },
  { id: 319, name: '(GMT+11) Pacific/Noumea' },
  { id: 320, name: '(GMT+11) Pacific/Pohnpei' },
  { id: 321, name: '(GMT+12) Asia/Anadyr' },
  { id: 322, name: '(GMT+12) Asia/Kamchatka' },
  { id: 323, name: '(GMT+12) Pacific/Auckland' },
  { id: 324, name: '(GMT+12) Pacific/Fiji' },
  { id: 325, name: '(GMT+12) Pacific/Funafuti' },
  { id: 326, name: '(GMT+12) Pacific/Kwajalein' },
  { id: 327, name: '(GMT+12) Pacific/Majuro' },
  { id: 328, name: '(GMT+12) Pacific/Nauru' },
  { id: 329, name: '(GMT+12) Pacific/Tarawa' },
  { id: 330, name: '(GMT+12) Pacific/Wake' },
  { id: 331, name: '(GMT+12) Pacific/Wallis' },
  { id: 332, name: '(GMT+12.75) Pacific/Chatham' },
  { id: 333, name: '(GMT+13) Pacific/Apia' },
  { id: 334, name: '(GMT+13) Pacific/Fakaofo' },
  { id: 335, name: '(GMT+13) Pacific/Kanton' },
  { id: 336, name: '(GMT+13) Pacific/Tongatapu' },
  { id: 337, name: '(GMT+14) Pacific/Kiritimati' }
]
